// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8mTUfHQKseN67FPtRqSS-VukDLBchpEU',
    appId: '1:375897161588:web:635ad0648237231d527621',
    messagingSenderId: '375897161588',
    projectId: 'admin-dashboard-30e2d',
    authDomain: 'admin-dashboard-30e2d.firebaseapp.com',
    storageBucket: 'admin-dashboard-30e2d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWAwtH7ICLlki4lJDGhYjBT4V2onVcnk0',
    appId: '1:375897161588:android:74ea6dc81bb2bd3e527621',
    messagingSenderId: '375897161588',
    projectId: 'admin-dashboard-30e2d',
    storageBucket: 'admin-dashboard-30e2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpf-_lmKkwwN-8LT_wMcNJ2qxPUwx7Izs',
    appId: '1:375897161588:ios:b77b8560ab5974e2527621',
    messagingSenderId: '375897161588',
    projectId: 'admin-dashboard-30e2d',
    storageBucket: 'admin-dashboard-30e2d.appspot.com',
    iosBundleId: 'com.example.tracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpf-_lmKkwwN-8LT_wMcNJ2qxPUwx7Izs',
    appId: '1:375897161588:ios:b77b8560ab5974e2527621',
    messagingSenderId: '375897161588',
    projectId: 'admin-dashboard-30e2d',
    storageBucket: 'admin-dashboard-30e2d.appspot.com',
    iosBundleId: 'com.example.tracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8mTUfHQKseN67FPtRqSS-VukDLBchpEU',
    appId: '1:375897161588:web:dd6afb58ecae9dc2527621',
    messagingSenderId: '375897161588',
    projectId: 'admin-dashboard-30e2d',
    authDomain: 'admin-dashboard-30e2d.firebaseapp.com',
    storageBucket: 'admin-dashboard-30e2d.appspot.com',
  );

}